/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;


class AboutTab: dfl.tabcontrol.TabPage
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.label.Label label1;
	dfl.label.Label label2;
	dfl.label.Label label8;
	dfl.label.Label label9;
	dfl.label.Label label10;
	dfl.label.Label label11;
	dfl.label.Label label12;
	dfl.label.Label label13;
	dfl.label.Label label14;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeAboutTab();
		
		//@  Other AboutTab initialization code here.
		
	}
	
	
	private void initializeAboutTab()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL TabPage
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "About the DApplication";
		label1.bounds = dfl.all.Rect(8, 8, 144, 16);
		label1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.text = "(c) 2011 Danny Arends";
		label2.bounds = dfl.all.Rect(8, 25, 144, 16);
		label2.parent = this;
		//~DFL dfl.label.Label=label8
		label8 = new dfl.label.Label();
		label8.name = "label8";
		label8.text = "This application was born as a testing initiative of the D programming language.";
		label8.bounds = dfl.all.Rect(8, 59, 456, 16);
		label8.parent = this;
		//~DFL dfl.label.Label=label9
		label9 = new dfl.label.Label();
		label9.name = "label9";
		label9.text = "It uses the CDC D one-file builder with dfl installed besides dmd 2.0";
		label9.bounds = dfl.all.Rect(8, 76, 456, 16);
		label9.parent = this;
		//~DFL dfl.label.Label=label10
		label10 = new dfl.label.Label();
		label10.name = "label10";
		label10.text = "The code wrapped is the any size tab separated TextFileReader";
		label10.bounds = dfl.all.Rect(8, 93, 456, 16);
		label10.parent = this;
		//~DFL dfl.label.Label=label11
		label11 = new dfl.label.Label();
		label11.name = "label11";
		label11.text = "The GUI also allows to covert any sized tab separated data files into xbinary format";
		label11.bounds = dfl.all.Rect(8, 110, 456, 16);
		label11.parent = this;
		//~DFL dfl.label.Label=label12
		label12 = new dfl.label.Label();
		label12.name = "label12";
		label12.text = " ";
		label12.bounds = dfl.all.Rect(8, 127, 456, 16);
		label12.parent = this;
		//~DFL dfl.label.Label=label13
		label13 = new dfl.label.Label();
		label13.name = "label13";
		label13.text = "Danny Arends";
		label13.bounds = dfl.all.Rect(8, 144, 456, 16);
		label13.parent = this;
		//~DFL dfl.label.Label=label14
		label14 = new dfl.label.Label();
		label14.name = "label14";
		label14.text = "--ooOOoo--";
		label14.textAlign = dfl.all.ContentAlignment.TOP_CENTER;
		label14.bounds = dfl.all.Rect(8, 42, 456, 16);
		label14.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

