/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import std.stdio;
import dfl.all;
import openfiletab;
import abouttab;


class DApplication: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.groupbox.GroupBox fileBox;
	dfl.button.Button openBtn;
	dfl.button.Button saveBtn;
	dfl.button.Button exitBtn;
	dfl.button.Button convertBtn;
	dfl.button.Button fileBtn;
	dfl.button.Button editBtn;
	dfl.button.Button helpBtn;
	dfl.textbox.TextBox debugBox;
	dfl.groupbox.GroupBox editBox;
	dfl.button.Button undoBtn;
	dfl.button.Button redoBtn;
	dfl.groupbox.GroupBox helpBox;
	dfl.button.Button helpTabBtn;
	dfl.button.Button aboutBtn;
	dfl.groupbox.GroupBox editBox2;
	dfl.button.Button topBar;
	dfl.tabcontrol.TabControl mainTabs;
	//~Entice Designer variables end here.
	
	OpenFileTab openFileTab;
	AboutTab aboutTab;
	
	this(){
		initializeDApplication();
		
		openFileTab = new OpenFileTab();
		openFileTab.text = "Open files";
		
		aboutTab = new AboutTab();
		aboutTab.text = "About";
	}
	
	
	private void initializeDApplication()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_SINGLE;
		text = "DApplication";
		clientSize = dfl.all.Size(594, 275);
		//~DFL dfl.groupbox.GroupBox=fileBox
		fileBox = new dfl.groupbox.GroupBox();
		fileBox.name = "fileBox";
		fileBox.visible = false;
		fileBox.bounds = dfl.all.Rect(0, 20, 72, 102);
		fileBox.parent = this;
		//~DFL dfl.button.Button=openBtn
		openBtn = new dfl.button.Button();
		openBtn.name = "openBtn";
		openBtn.text = "Open";
		openBtn.bounds = dfl.all.Rect(7, 13, 59, 20);
		openBtn.parent = fileBox;
		//~DFL dfl.button.Button=saveBtn
		saveBtn = new dfl.button.Button();
		saveBtn.name = "saveBtn";
		saveBtn.text = "Save";
		saveBtn.bounds = dfl.all.Rect(7, 34, 59, 20);
		saveBtn.parent = fileBox;
		//~DFL dfl.button.Button=exitBtn
		exitBtn = new dfl.button.Button();
		exitBtn.name = "exitBtn";
		exitBtn.text = "Exit";
		exitBtn.bounds = dfl.all.Rect(7, 76, 59, 20);
		exitBtn.parent = fileBox;
		//~DFL dfl.button.Button=convertBtn
		convertBtn = new dfl.button.Button();
		convertBtn.name = "convertBtn";
		convertBtn.text = "Convert";
		convertBtn.bounds = dfl.all.Rect(7, 55, 59, 20);
		convertBtn.parent = fileBox;
		//~DFL dfl.button.Button=fileBtn
		fileBtn = new dfl.button.Button();
		fileBtn.name = "fileBtn";
		fileBtn.text = "File";
		fileBtn.bounds = dfl.all.Rect(0, 0, 72, 20);
		fileBtn.parent = this;
		//~DFL dfl.button.Button=editBtn
		editBtn = new dfl.button.Button();
		editBtn.name = "editBtn";
		editBtn.text = "Edit";
		editBtn.bounds = dfl.all.Rect(72, 0, 72, 20);
		editBtn.parent = this;
		//~DFL dfl.button.Button=helpBtn
		helpBtn = new dfl.button.Button();
		helpBtn.name = "helpBtn";
		helpBtn.text = "Help";
		helpBtn.bounds = dfl.all.Rect(144, 0, 72, 20);
		helpBtn.parent = this;
		//~DFL dfl.textbox.TextBox=debugBox
		debugBox = new dfl.textbox.TextBox();
		debugBox.name = "debugBox";
		debugBox.multiline = true;
		debugBox.bounds = dfl.all.Rect(8, 216, 576, 56);
		debugBox.parent = this;
		//~DFL dfl.groupbox.GroupBox=editBox
		editBox = new dfl.groupbox.GroupBox();
		editBox.name = "editBox";
		editBox.visible = false;
		editBox.bounds = dfl.all.Rect(72, 20, 72, 58);
		editBox.parent = this;
		//~DFL dfl.button.Button=undoBtn
		undoBtn = new dfl.button.Button();
		undoBtn.name = "undoBtn";
		undoBtn.text = "Undo";
		undoBtn.bounds = dfl.all.Rect(7, 13, 59, 20);
		undoBtn.parent = editBox;
		//~DFL dfl.button.Button=redoBtn
		redoBtn = new dfl.button.Button();
		redoBtn.name = "redoBtn";
		redoBtn.text = "Redo";
		redoBtn.bounds = dfl.all.Rect(7, 34, 59, 20);
		redoBtn.parent = editBox;
		//~DFL dfl.groupbox.GroupBox=helpBox
		helpBox = new dfl.groupbox.GroupBox();
		helpBox.name = "helpBox";
		helpBox.visible = false;
		helpBox.bounds = dfl.all.Rect(144, 20, 72, 58);
		helpBox.parent = this;
		//~DFL dfl.button.Button=helpTabBtn
		helpTabBtn = new dfl.button.Button();
		helpTabBtn.name = "helpTabBtn";
		helpTabBtn.text = "Help";
		helpTabBtn.bounds = dfl.all.Rect(7, 13, 59, 20);
		helpTabBtn.parent = helpBox;
		//~DFL dfl.button.Button=aboutBtn
		aboutBtn = new dfl.button.Button();
		aboutBtn.name = "aboutBtn";
		aboutBtn.text = "About";
		aboutBtn.bounds = dfl.all.Rect(7, 34, 59, 20);
		aboutBtn.parent = helpBox;
		//~DFL dfl.groupbox.GroupBox=editBox2
		editBox2 = new dfl.groupbox.GroupBox();
		editBox2.name = "editBox2";
		editBox2.visible = false;
		editBox2.bounds = dfl.all.Rect(72, 74, 72, 64);
		editBox2.parent = this;
		//~DFL dfl.button.Button=topBar
		topBar = new dfl.button.Button();
		topBar.name = "topBar";
		topBar.dock = dfl.all.DockStyle.TOP;
		topBar.enabled = false;
		topBar.bounds = dfl.all.Rect(0, 0, 594, 20);
		topBar.parent = this;
		//~DFL dfl.tabcontrol.TabControl=mainTabs
		mainTabs = new dfl.tabcontrol.TabControl();
		mainTabs.name = "mainTabs";
		mainTabs.bounds = dfl.all.Rect(8, 24, 576, 184);
		mainTabs.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
		fileBtn.click ~= &FileMenuButton_click;
		editBtn.click ~= &EditMenuButton_click;
		helpBtn.click ~= &HelpMenuButton_click;
		openBtn.click ~= &OpenTabButton_click;
		aboutBtn.click ~= &AboutTabButton_click;
	}
  
  // My event handler.
  private void AboutTabButton_click(Control sender, EventArgs ea){
  	debugBox.appendText("You clicked button: " ~ sender.toString() ~ "\n");
    if(!mainTabs.tabPages.contains(aboutTab)){
    	aboutTab.parent=null;
    	mainTabs.tabPages.add(aboutTab);
    }else{
    	mainTabs.tabPages.remove(aboutTab);
    }
  }
  
  private void OpenTabButton_click(Control sender, EventArgs ea){
  	debugBox.appendText("You clicked button: " ~ sender.toString() ~ "\n");
    if(!mainTabs.tabPages.contains(openFileTab)){
    	openFileTab.parent=null;
    	mainTabs.tabPages.add(openFileTab);
   }else{
    	mainTabs.tabPages.remove(openFileTab);
    }
  }
  
  private void FileMenuButton_click(Control sender, EventArgs ea){
    debugBox.appendText("You clicked button: " ~ sender.toString() ~ "\n");
    fileBox.visible(!fileBox.visible());
	editBox.visible(false);
    editBox2.visible(false);
    helpBox.visible(false);
  }
  
  private void EditMenuButton_click(Control sender, EventArgs ea){
    debugBox.appendText("You clicked button: " ~ sender.toString() ~ "\n");
    fileBox.visible(false);
    editBox.visible(!editBox.visible());
    editBox2.visible(!editBox2.visible());
    helpBox.visible(false);
  }
  
  private void HelpMenuButton_click(Control sender, EventArgs ea){
    debugBox.appendText("You clicked button: " ~ sender.toString() ~ "\n");
    fileBox.visible(false);
	editBox.visible(false);
    editBox2.visible(false);
    helpBox.visible(!helpBox.visible());
  }
}


int main()
{
	int result = 0;
	
	try
	{
		//Application.enableVisualStyles();
		
		//@  Other application initialization code here.
		
		Application.run(new DApplication());
	}
	catch(Throwable o)
	{
		msgBox(o.toString(), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);
		
		result = 1;
	}
	
	return result;
}

