/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;


class OpenFileTab: dfl.tabcontrol.TabPage
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.textbox.TextBox filenameBox;
	dfl.button.Button selectBtn;
	dfl.button.Button parseBtn;
	dfl.button.Button rowBtn;
	dfl.textbox.TextBox col_start;
	dfl.button.Button subMatrixBtn;
	dfl.textbox.TextBox row_start;
	dfl.button.Button itemBtn;
	dfl.textbox.TextBox row_end;
	dfl.textbox.TextBox col_end;
	dfl.label.Label label1;
	dfl.label.Label label2;
	dfl.button.Button colBtn;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeFile();
		
		//@  Other File initialization code here.
		
	}
	
	
	private void initializeFile()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL TabPage
		//~DFL dfl.textbox.TextBox=filenameBox
		filenameBox = new dfl.textbox.TextBox();
		filenameBox.name = "filenameBox";
		filenameBox.bounds = dfl.all.Rect(8, 8, 128, 24);
		filenameBox.parent = this;
		//~DFL dfl.button.Button=selectBtn
		selectBtn = new dfl.button.Button();
		selectBtn.name = "selectBtn";
		selectBtn.text = "Select File";
		selectBtn.bounds = dfl.all.Rect(154, 8, 96, 24);
		selectBtn.parent = this;
		//~DFL dfl.button.Button=parseBtn
		parseBtn = new dfl.button.Button();
		parseBtn.name = "parseBtn";
		parseBtn.text = "Parse Properties";
		parseBtn.bounds = dfl.all.Rect(253, 8, 96, 24);
		parseBtn.parent = this;
		//~DFL dfl.button.Button=rowBtn
		rowBtn = new dfl.button.Button();
		rowBtn.name = "rowBtn";
		rowBtn.text = "Row";
		rowBtn.bounds = dfl.all.Rect(8, 48, 64, 24);
		rowBtn.parent = this;
		//~DFL dfl.textbox.TextBox=col_start
		col_start = new dfl.textbox.TextBox();
		col_start.name = "col_start";
		col_start.bounds = dfl.all.Rect(89, 80, 48, 24);
		col_start.parent = this;
		//~DFL dfl.button.Button=subMatrixBtn
		subMatrixBtn = new dfl.button.Button();
		subMatrixBtn.name = "subMatrixBtn";
		subMatrixBtn.text = "SubMatrix";
		subMatrixBtn.bounds = dfl.all.Rect(280, 80, 64, 24);
		subMatrixBtn.parent = this;
		//~DFL dfl.textbox.TextBox=row_start
		row_start = new dfl.textbox.TextBox();
		row_start.name = "row_start";
		row_start.bounds = dfl.all.Rect(88, 48, 48, 24);
		row_start.parent = this;
		//~DFL dfl.button.Button=itemBtn
		itemBtn = new dfl.button.Button();
		itemBtn.name = "itemBtn";
		itemBtn.text = "Item";
		itemBtn.bounds = dfl.all.Rect(280, 48, 64, 24);
		itemBtn.parent = this;
		//~DFL dfl.textbox.TextBox=row_end
		row_end = new dfl.textbox.TextBox();
		row_end.name = "row_end";
		row_end.bounds = dfl.all.Rect(216, 48, 48, 24);
		row_end.parent = this;
		//~DFL dfl.textbox.TextBox=col_end
		col_end = new dfl.textbox.TextBox();
		col_end.name = "col_end";
		col_end.bounds = dfl.all.Rect(217, 80, 48, 24);
		col_end.parent = this;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "...";
		label1.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label1.bounds = dfl.all.Rect(145, 48, 60, 24);
		label1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.text = "...";
		label2.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label2.bounds = dfl.all.Rect(146, 80, 60, 24);
		label2.parent = this;
		//~DFL dfl.button.Button=colBtn
		colBtn = new dfl.button.Button();
		colBtn.name = "colBtn";
		colBtn.text = "Col";
		colBtn.bounds = dfl.all.Rect(8, 80, 64, 24);
		colBtn.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

