/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;


class OpenFileTab: dfl.tabcontrol.TabPage
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.textbox.TextBox textBox2;
	dfl.button.Button button4;
	dfl.button.Button button5;
	dfl.button.Button button6;
	dfl.textbox.TextBox textBox3;
	dfl.button.Button button8;
	dfl.textbox.TextBox textBox4;
	dfl.button.Button button10;
	dfl.textbox.TextBox textBox5;
	dfl.textbox.TextBox textBox6;
	dfl.label.Label label1;
	dfl.label.Label label2;
	dfl.button.Button button11;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeFile();
		
		//@  Other File initialization code here.
		
	}
	
	
	private void initializeFile()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL TabPage
		//~DFL dfl.textbox.TextBox=textBox2
		textBox2 = new dfl.textbox.TextBox();
		textBox2.name = "textBox2";
		textBox2.bounds = dfl.all.Rect(8, 16, 128, 24);
		textBox2.parent = this;
		//~DFL dfl.button.Button=button4
		button4 = new dfl.button.Button();
		button4.name = "button4";
		button4.text = "Select File";
		button4.bounds = dfl.all.Rect(154, 16, 96, 24);
		button4.parent = this;
		//~DFL dfl.button.Button=button5
		button5 = new dfl.button.Button();
		button5.name = "button5";
		button5.text = "Parse Properties";
		button5.bounds = dfl.all.Rect(253, 16, 96, 24);
		button5.parent = this;
		//~DFL dfl.button.Button=button6
		button6 = new dfl.button.Button();
		button6.name = "button6";
		button6.text = "Row";
		button6.bounds = dfl.all.Rect(8, 48, 64, 24);
		button6.parent = this;
		//~DFL dfl.textbox.TextBox=textBox3
		textBox3 = new dfl.textbox.TextBox();
		textBox3.name = "textBox3";
		textBox3.bounds = dfl.all.Rect(89, 80, 48, 24);
		textBox3.parent = this;
		//~DFL dfl.button.Button=button8
		button8 = new dfl.button.Button();
		button8.name = "button8";
		button8.text = "SubMatrix";
		button8.bounds = dfl.all.Rect(280, 80, 64, 24);
		button8.parent = this;
		//~DFL dfl.textbox.TextBox=textBox4
		textBox4 = new dfl.textbox.TextBox();
		textBox4.name = "textBox4";
		textBox4.bounds = dfl.all.Rect(88, 48, 48, 24);
		textBox4.parent = this;
		//~DFL dfl.button.Button=button10
		button10 = new dfl.button.Button();
		button10.name = "button10";
		button10.text = "Item";
		button10.bounds = dfl.all.Rect(280, 48, 64, 24);
		button10.parent = this;
		//~DFL dfl.textbox.TextBox=textBox5
		textBox5 = new dfl.textbox.TextBox();
		textBox5.name = "textBox5";
		textBox5.bounds = dfl.all.Rect(216, 48, 48, 24);
		textBox5.parent = this;
		//~DFL dfl.textbox.TextBox=textBox6
		textBox6 = new dfl.textbox.TextBox();
		textBox6.name = "textBox6";
		textBox6.bounds = dfl.all.Rect(217, 80, 48, 24);
		textBox6.parent = this;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "...";
		label1.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label1.bounds = dfl.all.Rect(145, 48, 60, 24);
		label1.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.text = "...";
		label2.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label2.bounds = dfl.all.Rect(146, 80, 60, 24);
		label2.parent = this;
		//~DFL dfl.button.Button=button11
		button11 = new dfl.button.Button();
		button11.name = "button11";
		button11.text = "Row";
		button11.bounds = dfl.all.Rect(8, 80, 64, 24);
		button11.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

