/*
    Generated by Entice Designer
    Entice Designer written by Christopher E. Miller
    www.dprogramming.com/entice.php
*/

private import dfl.all;
import std.stdio;
import std.conv;

import gui.opengl.glengine;
import gui.opengl.gltimer;
import gui.opengl.glcontrol;

class mainForm: dfl.form.Form
{
    // Do not modify or move this block of variables.
    //~Entice Designer variables begin here.
	GLControl glcontrol;
	dfl.textbox.TextBox textBox1;
	dfl.groupbox.GroupBox groupBox1;
	//~Entice Designer variables end here.
    glTimer gameloop;
    
    this(){
      createMenu();
      initializeOpengltest();
      // Other opengltest initialization code here.
      gameloop = new glTimer(210, glcontrol);
      gameloop.start();
      addShortcut(Keys.LEFT, &glKey); 
      addShortcut(Keys.RIGHT, &glKey);
      addShortcut(Keys.UP, &glKey);
      addShortcut(Keys.DOWN, &glKey);
      addShortcut(Keys.SPACE, &glKey);
      addShortcut(Keys.TAB, &glKey);
      addShortcut(Keys.ENTER, &glKey);
      addShortcut(Keys.ESCAPE, &fileExitClick);
    }
    
    protected void createMenu(){
      this.menu = new MainMenu;
        
      auto mmenu1 = new MenuItem;
      mmenu1.text = "&File";
      this.menu.menuItems.add(mmenu1);
      
      auto mi11 = new MenuItem;
      mi11.text = "&Open";
      mi11.click ~= &fileOpenClick;
      mmenu1.menuItems.add(mi11);
      
      auto mi12 = new MenuItem;
      mi12.text = "&Save";
      mi12.click ~= &fileSaveClick;
      mmenu1.menuItems.add(mi12);
      
      auto mi13 = new MenuItem;
      mi13.text = "E&xit";
      mi13.click ~= &fileExitClick;
      mmenu1.menuItems.add(mi13);
      
      auto mmenu2 = new MenuItem;
      mmenu2.text = "&Edit";
      this.menu.menuItems.add(mmenu2);
      
      auto mi21 = new MenuItem;
      mi21.text = "&Map";
      mmenu2.menuItems.add(mi21);
      
      auto mmenu3 = new MenuItem;
      mmenu3.text = "&Settings";
      this.menu.menuItems.add(mmenu3);
      
      auto mi31 = new MenuItem;
      mi31.text = "&Graphics";
      mmenu3.menuItems.add(mi31);
      
      auto mmenu4 = new MenuItem;
      mmenu4.text = "?";
      this.menu.menuItems.add(mmenu4);
        
      auto mi41 = new MenuItem;
      mi41.text = "&About";
      mmenu4.menuItems.add(mi41);
      
      auto mi42 = new MenuItem;
      mi42.text = "&Help";
      mmenu4.menuItems.add(mi42);
    }

    
    private void initializeOpengltest(){
        // Do not manually modify this function.
        //~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_SINGLE;
		text = "D openGL Framework";
		clientSize = dfl.all.Size(1004, 685);
		//~DFL GLControl:dfl.label.Label=glcontrol
		glcontrol = new RenderingEngine();
		glcontrol.name = "glcontrol";
		glcontrol.bounds = dfl.all.Rect(201, 8, 800, 600);
		glcontrol.parent = this;
		//~DFL dfl.textbox.TextBox=textBox1
		textBox1 = new dfl.textbox.TextBox();
		textBox1.name = "textBox1";
		textBox1.dock = dfl.all.DockStyle.BOTTOM;
		textBox1.multiline = true;
		textBox1.readOnly = true;
		textBox1.bounds = dfl.all.Rect(0, 613, 1004, 72);
		textBox1.parent = this;
		//~DFL dfl.groupbox.GroupBox=groupBox1
		groupBox1 = new dfl.groupbox.GroupBox();
		groupBox1.name = "groupBox1";
		groupBox1.dock = dfl.all.DockStyle.LEFT;
		groupBox1.bounds = dfl.all.Rect(0, 0, 192, 613);
		groupBox1.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
    }

  void fileExitClick(Object sender, EventArgs ea){
    writefln("Shutdown");
    Application.exitThread();
  }
  
  void fileSaveClick(Object sender, EventArgs ea){
    writefln("FileSave clicked");
  }
  
  void fileOpenClick(Object sender, EventArgs ea){
    writefln("FileOpen clicked");
  }
  
  void glKey(Object sender, FormShortcutEventArgs ea){
    switch(ea.shortcut){
      case Keys.LEFT:  writeln("Left");
      break;
      case Keys.RIGHT: writeln("Right");
      break;
      case Keys.UP:    writeln("Up");
      break;
      case Keys.DOWN:  writeln("Down");
      break;
      case Keys.SPACE: writeln("Space");
      break;
      case Keys.TAB:   writeln("Tab");
      break;
      case Keys.ENTER: writeln("Enter");
      break;
    }
  }

  protected:
}


int main(){
  int result = 0;
  try{
    Application.run(new mainForm());
  }catch(Throwable o){
    msgBox(o.toString(), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);
    result = 1;
  }
  return result;
}
