char a[5] = [65, 66, 67, 68 , 69];
int b = (12 * (12 + 6) - 15);
int c = true && 1;

int sum(int x, int y){
  return(x+y);
}

int main(){
  int x = 0;
  int y[512];
  int y2;

  printc(a[3]);
  printc(a[0]);
  printc(a[4]);
  a[0] = a[4];
  printc(a[0]);

  if(x < 16 && true){
    print(1);
  }else{
    print(11);
  }

  y[0] = sum(x, -2);
  print(sum(x, 2));
  print(y[0]);
  while(x >= 0){
    print(x);
    x = x - 1;
  }
  return(y);
}

